=== lipenglong24/project/spring/lspring/src/main/resources/lspring.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/lspring"
           xmlns="http://www.example.org/lspring"
           elementFormDefault="qualified">
    <xs:element name="beans" type="beansType"></xs:element>

    <xs:complexType name="beansType">
        <xs:sequence>
            <xs:element name="bean" type="beanType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="aop" type="aopType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="component-scan" type="component-scanType"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="beanType">
        <xs:sequence>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transaction" type="transactionType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attributeGroup ref="refValueType"/>
    </xs:complexType>

    <xs:complexType name="transactionType">
        <xs:sequence>
            <xs:element name="method" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="aopType">
        <xs:attribute name="package" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:attributeGroup name="refValueType">
        <xs:attribute name="ref" type="xs:string" use="optional"/>
        <xs:attribute name="value" type="xs:anyType" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="component-scanType">
        <xs:attribute name="base-package" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== lipenglong24/project/spring/lspring/src/test/resources/bean-context-xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.example.org/lspring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.org/lspring
       ./lspring.xsd">

    <bean name="dataSource" class="com.lipenglong.lspring.jdbc.JdbcTemplate">
        <property name="driverClassName" value="org.hsqldb.jdbcDriver"/>
        <property name="url" value="jdbc:hsqldb:./target/work/t5_tutorial1;shutdown=true"/>
        <property name="username" value="sa"/>
        <property name="password" value=""/>
    </bean>
    <bean name="transactionManager" class="com.lipenglong.lspring.jdbc.TransactionHandler">
        <property name="dataSource" ref="dataSource"/>
    </bean>

    <bean name="userDao" class="com.lipenglong.lspring.dao.UserDaoImpl">
        <property name="jdbcTemplate" ref="dataSource"></property>
    </bean>
    <bean name="userService" class="com.lipenglong.lspring.service.UserServiceImpl">
        <property name="userDao" ref="userDao"></property>
        <transaction>
            <method>getUserList</method>
            <method>addUser</method>
            <method>print</method>
        </transaction>
    </bean>
    <bean name="userAction" class="com.lipenglong.lspring.action.UserAction">
        <property name="userService" ref="userService"></property>
    </bean>

    <aop package="com.lipenglong.lspring.service"></aop>
</beans>

=== lipenglong24/project/spring/lspring/src/test/resources/bean-context-annotation.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.example.org/lspring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.org/lspring
       ./lspring.xsd">

    <bean name="dataSource" class="com.lipenglong.lspring.jdbc.JdbcTemplate">
        <property name="driverClassName" value="org.hsqldb.jdbcDriver"/>
        <property name="url" value="jdbc:hsqldb:./target/work/t5_tutorial1;shutdown=true"/>
        <property name="username" value="sa"/>
        <property name="password" value=""/>
    </bean>
    <bean name="transactionManager" class="com.lipenglong.lspring.jdbc.TransactionHandler">
        <property name="dataSource" ref="dataSource"/>
    </bean>

    <aop package="com.lipenglong.lspring.service"></aop>
    <component-scan base-package="com.lipenglong.lspring"/>
</beans>
